### ISSUE TITLE
Apollo hooks

### ISSUE THREAD

**Issue by dunatron** [dai-shi/typescript-expo-apollo-boilerplate#3]
Any chance you would be able to get Apollo hooks going? I found this fantastic, but still cant get hooks to work, even when updating the packages etc

**Comment by dai-shi** [comment]
Hmmmm, I don't feel like updating this repository to the latest packages. It should be so easy now. Did you try the latest Expo?

**Comment by dunatron** [comment]
Fair enough, I am giving it a go atm. Agreed it should be fairly easy but its not. the useQuery seems to work ok, but useMutation not so much.

**Comment by dai-shi** [comment]
BTW, Apollo Client v3 will also be released hopefully soon. Personally, I will give it a try.

Closing this issue, but happy to keep discussing about this topic.

**Comment by dai-shi** [comment]
Hi @dunatron !

I happened to need to do this. Here you go:
https://github.com/dai-shi/typescript-expo-apollo-boilerplate/tree/v2
It's with the latest Expo, Apollo Client beta and React Navigation beta 😄 .
